name: Integration

on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      - name: Additional R package dependencies
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install R packages
        run: Rscript -e 'install.packages(c("XML", "httr"))'
      - run: Rscript base/workflow/inst/make-test-xmls.R base/workflow/inst/default_tests.csv
      - name: Setup and launch Docker stack
        run: |
          echo 'PECAN_VERSION=develop' > .env
          echo 'BETY_VERSION=develop' >> .env
          docker-compose up -d postgres
          docker run --rm --network pecan_pecan pecan/db
          docker-compose run --rm bety user carya illinois "Demo admin" carya@example.com 1 1
          docker run --rm --network pecan_pecan --volume pecan_pecan:/data --env FQDN=docker pecan/data:develop
          docker-compose up -d
          # Wait for RabbitMQ to launch
          until $(docker-compose logs rabbitmq | grep -q "accepting AMQP connection"); do
            echo "Waiting for RabbitMQ..."
            sleep 3
          done
          echo "Done!"
      - name: Run integration tests
        run: bash base/workflow/inst/run-integration.sh
      - name: Save results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/api/*
